"""Load the organizer's DOGFOOD fixture into a local development database."""

import argparse
import json
import os
import secrets
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from pathlib import Path
from uuid import UUID, NAMESPACE_URL, uuid5

from sqlalchemy import delete, select
from sqlalchemy.orm import Session

from app.core.config import get_settings
from app.core.security import create_access_token, hash_password
from app.db.session import SessionLocal, get_engine
from app.models import (
    Event,
    EventRegistration,
    EventTrack,
    JudgeCriterionScore,
    JudgeEvaluation,
    JudgeEventAssignment,
    JudgeProjectAssignment,
    JudgingProjectResult,
    JudgingResultSnapshot,
    JudgingRubric,
    JudgingRubricCriterion,
    ProjectSubmission,
    Team,
    TeamInvitation,
    TeamMember,
    User,
)

_NAMESPACE = NAMESPACE_URL
_EVENT_KEY = "evt_01"
_COOKIE = "codearena_access"


def _id(kind: str, source_id: str) -> UUID:
    return uuid5(_NAMESPACE, f"codearena-dogfood:{kind}:{source_id}")


def _date(value: str) -> datetime:
    return datetime.fromisoformat(value.replace("Z", "+00:00"))


def _user(db: Session, email: str, name: str, role: str) -> User:
    normalized = email.strip().casefold()
    user = db.scalar(select(User).where(User.email == normalized))
    if user is None:
        user = User(
            id=_id("user", normalized),
            email=normalized,
            password_hash=hash_password(secrets.token_urlsafe(32)),
            display_name=name[:100],
            role=role,
            is_active=True,
        )
        db.add(user)
        db.flush()
    else:
        user.display_name = name[:100]
        user.role = role
        user.is_active = True
    return user


def _clear_event(db: Session, event_id: UUID) -> None:
    score_ids = select(JudgeEvaluation.id).where(JudgeEvaluation.event_id == event_id)
    db.execute(delete(JudgeCriterionScore).where(JudgeCriterionScore.evaluation_id.in_(score_ids)))
    db.execute(delete(JudgeEvaluation).where(JudgeEvaluation.event_id == event_id))
    db.execute(delete(JudgeProjectAssignment).where(JudgeProjectAssignment.event_id == event_id))
    snapshot_ids = select(JudgingResultSnapshot.id).where(
        JudgingResultSnapshot.event_id == event_id
    )
    db.execute(delete(JudgingProjectResult).where(JudgingProjectResult.snapshot_id.in_(snapshot_ids)))
    db.execute(delete(JudgingResultSnapshot).where(JudgingResultSnapshot.event_id == event_id))
    db.execute(delete(JudgingRubricCriterion).where(JudgingRubricCriterion.event_id == event_id))
    db.execute(delete(JudgingRubric).where(JudgingRubric.event_id == event_id))
    db.execute(delete(JudgeEventAssignment).where(JudgeEventAssignment.event_id == event_id))
    db.execute(delete(ProjectSubmission).where(ProjectSubmission.event_id == event_id))
    db.execute(delete(TeamInvitation).where(TeamInvitation.event_id == event_id))
    db.execute(delete(TeamMember).where(TeamMember.event_id == event_id))
    db.execute(delete(Team).where(Team.event_id == event_id))
    db.execute(delete(EventRegistration).where(EventRegistration.event_id == event_id))
    db.execute(delete(EventTrack).where(EventTrack.event_id == event_id))
    db.execute(delete(Event).where(Event.id == event_id))


def _make_demo_config(path: Path, event_id: UUID, role_users: dict[str, User]) -> None:
    settings = get_settings()
    if not settings.jwt_secret_key:
        raise RuntimeError("JWT_SECRET_KEY must be configured to seed local credentials")
    headers = {
        role: f"Cookie: {_COOKIE}={create_access_token(user.id, expires_delta=timedelta(days=7))}"
        for role, user in role_users.items()
    }
    base_url = os.environ.get("DOGFOOD_BASE_URL", "http://127.0.0.1:8002")
    content = f'''# Local-only credentials; generated by the DOGFOOD fixture seeder.
[portal]
base_url = "{base_url}"

[tiers]
claimed = ["T1", "T2"]
pitch = "A self-hostable hackathon portal with event-scoped human judging."

[auth]
organizer = "{headers["organizer"]}"
judge_a = "{headers["judge_a"]}"
judge_b = "{headers["judge_b"]}"
participant = "{headers["participant"]}"

[routes]
gallery = "/api/v1/gallery/projects"
submit = "/api/v1/events/{event_id}/projects"
judge_scores = "/api/v1/judging/scores"
peer_scores = "/api/v1/judging/scores?judge=judge_a"
csv_export = "/api/v1/events/{event_id}/judging/results.csv"
'''
    path.write_text(content, encoding="utf-8")
    path.chmod(0o600)


def seed(fixture_path: Path, config_path: Path) -> dict[str, int]:
    fixture = json.loads(fixture_path.read_text(encoding="utf-8"))
    event_id = _id("event", fixture["event"]["id"])
    db = SessionLocal(bind=get_engine())
    try:
        _clear_event(db, event_id)

        organizer = _user(db, "organizer@dogfood.local", "DOGFOOD Organizer", "organizer")
        user_by_email: dict[str, User] = {}
        participant_emails = {
            email.casefold()
            for team in fixture["teams"]
            for email in team["members"]
        }
        for judge in fixture["judges"]:
            user = _user(db, judge["email"], judge["name"], "participant")
            user_by_email[judge["email"].casefold()] = user
        for email in sorted(participant_emails):
            name = email.split("@", 1)[0].replace("_", " ").replace(".", " ").title()
            user_by_email[email] = _user(db, email, name, "participant")

        event = Event(
            id=event_id,
            organizer_id=organizer.id,
            title=fixture["event"]["name"],
            slug="sample-hack-2026-demo",
            description="Local DOGFOOD fixture event.",
            status="active",
            registration_opens_at=datetime(2026, 1, 1, tzinfo=timezone.utc),
            registration_deadline=datetime(2026, 2, 1, tzinfo=timezone.utc),
            starts_at=datetime(2026, 2, 1, tzinfo=timezone.utc),
            submission_deadline=_date(fixture["event"]["submissions_close"]),
            ends_at=datetime(2026, 12, 1, tzinfo=timezone.utc),
            team_min_size=1,
            team_max_size=4,
        )
        db.add(event)
        db.flush()

        track_ids: dict[str, UUID] = {}
        for track in fixture["tracks"]:
            track_id = _id("track", track["id"])
            db.add(EventTrack(id=track_id, event_id=event_id, source_id=track["id"], name=track["name"]))
            track_ids[track["id"]] = track_id

        registration_ids: set[UUID] = set()
        team_ids: dict[str, UUID] = {}
        team_sources = {team["id"]: team for team in fixture["teams"]}
        for team in fixture["teams"]:
            team_id = _id("team", team["id"])
            team_ids[team["id"]] = team_id
            member_users = [user_by_email[email.casefold()] for email in team["members"]]
            for member in member_users:
                if member.id not in registration_ids:
                    db.add(EventRegistration(event_id=event_id, user_id=member.id))
                    registration_ids.add(member.id)
            db.add(
                Team(
                    id=team_id,
                    event_id=event_id,
                    name=team["name"],
                    captain_id=member_users[0].id,
                )
            )
            db.flush()
            db.add_all(
                [
                    TeamMember(event_id=event_id, user_id=member.id, team_id=team_id)
                    for member in member_users
                ]
            )

        project_by_source: dict[str, ProjectSubmission] = {}
        projects_per_team: dict[str, int] = {}
        for project in fixture["projects"]:
            projects_per_team[project["team"]] = projects_per_team.get(project["team"], 0) + 1
            team_id = team_ids[project["team"]]
            if projects_per_team[project["team"]] > 1:
                # The app normally permits one project per team; retain every fixture
                # entry by giving additional entries a deterministic display-equivalent team.
                team_id = _id("duplicate-team", project["id"])
                source_team = team_sources[project["team"]]
                db.add(
                    Team(
                        id=team_id,
                        event_id=event_id,
                        name=source_team["name"],
                        captain_id=user_by_email[source_team["members"][0].casefold()].id,
                    )
                )
                db.flush()
            submitted_at = _date(project["submitted_at"])
            row = ProjectSubmission(
                id=_id("project", project["id"]),
                event_id=event_id,
                team_id=team_id,
                track_id=track_ids[project["track"]],
                title=project["title"],
                description=project["summary"],
                repository_url=project["repo_url"],
                status="submitted",
                submitted_at=submitted_at,
                created_at=submitted_at,
                updated_at=submitted_at,
            )
            db.add(row)
            project_by_source[project["id"]] = row
        db.flush()

        rubric_id = _id("rubric", fixture["event"]["id"])
        rubric = JudgingRubric(
            id=rubric_id,
            event_id=event_id,
            version=1,
            title="DOGFOOD fixture rubric",
            status="active",
            created_by=organizer.id,
            activated_at=datetime.now(timezone.utc),
        )
        db.add(rubric)
        criterion_ids: dict[str, UUID] = {}
        criteria = (
            ("functionality", "Functionality", "40", 0),
            ("quality", "Quality", "35", 1),
            ("innovation", "Innovation", "25", 2),
        )
        for source_key, name, weight, position in criteria:
            criterion_id = _id("criterion", source_key)
            criterion_ids[source_key] = criterion_id
            db.add(
                JudgingRubricCriterion(
                    id=criterion_id,
                    rubric_id=rubric_id,
                    event_id=event_id,
                    name=name,
                    description=f"Fixture criterion: {name.lower()}.",
                    weight=weight,
                    max_score=5,
                    position=position,
                )
            )
        db.flush()

        judge_ids: dict[str, User] = {}
        for judge in fixture["judges"]:
            judge_user = user_by_email[judge["email"].casefold()]
            judge_ids[judge["id"]] = judge_user
            db.add(
                JudgeEventAssignment(
                    id=_id("event-judge", judge["id"]),
                    event_id=event_id,
                    judge_id=judge_user.id,
                    assigned_by=organizer.id,
                    status="active",
                )
            )
        db.flush()

        for score in fixture["scores"]:
            assignment_id = _id("assignment", f"{score['judge']}:{score['project']}")
            judge_user = judge_ids[score["judge"]]
            project_row = project_by_source[score["project"]]
            db.add(
                JudgeProjectAssignment(
                    id=assignment_id,
                    event_id=event_id,
                    project_id=project_row.id,
                    judge_id=judge_user.id,
                    rubric_id=rubric_id,
                    assigned_by=organizer.id,
                    status="submitted",
                )
            )
            db.flush()
            score_values = score.get("criteria") or {}
            weighted = sum(
                (Decimal(score_values[key]) / Decimal("5")) * Decimal(weight)
                for key, _name, weight, _position in criteria
                if key in score_values
            )
            complete = all(key in score_values for key, *_ in criteria)
            evaluation_id = _id("evaluation", f"{score['judge']}:{score['project']}")
            db.add(
                JudgeEvaluation(
                    id=evaluation_id,
                    assignment_id=assignment_id,
                    event_id=event_id,
                    judge_id=judge_user.id,
                    rubric_id=rubric_id,
                    status="submitted" if complete else "draft",
                    feedback=score.get("comment", ""),
                    weighted_score=weighted.quantize(Decimal("0.0001")) if complete else None,
                    submitted_at=_date(
                        next(item["submitted_at"] for item in fixture["projects"] if item["id"] == score["project"])
                    ) if complete else None,
                )
            )
            db.flush()
            for criterion_key, raw_score in score_values.items():
                db.add(
                    JudgeCriterionScore(
                        id=_id("criterion-score", f"{score['judge']}:{score['project']}:{criterion_key}"),
                        evaluation_id=evaluation_id,
                        criterion_id=criterion_ids[criterion_key],
                        rubric_id=rubric_id,
                        raw_score=raw_score,
                    )
                )

        db.commit()
        roles = {
            "organizer": organizer,
            "judge_a": judge_ids[fixture["judges"][0]["id"]],
            "judge_b": judge_ids[fixture["judges"][1]["id"]],
            "participant": user_by_email[fixture["teams"][0]["members"][0].casefold()],
        }
        _make_demo_config(config_path, event_id, roles)
        return {
            "tracks": len(fixture["tracks"]),
            "judges": len(fixture["judges"]),
            "teams": len(fixture["teams"]),
            "projects": len(fixture["projects"]),
            "scores": len(fixture["scores"]),
        }
    except Exception:
        db.rollback()
        raise
    finally:
        db.close()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("fixture", type=Path)
    parser.add_argument("--config", type=Path, required=True)
    args = parser.parse_args()
    counts = seed(args.fixture, args.config)
    print("DOGFOOD fixture loaded: " + ", ".join(f"{key}={value}" for key, value in counts.items()))
    print(f"Local role headers written to {args.config}")


if __name__ == "__main__":
    main()
