import { useState } from 'react';
import type { FormEvent } from 'react';
import { useOrganizer } from '../../organizer/OrganizerProvider';
import type { RubricCriterion } from '../../judge/data';
function RubricEditor({ initial }: { initial: RubricCriterion[] }) {
  const { busy, saveRubric } = useOrganizer(); const [criteria,setCriteria] = useState(initial);
  const total = criteria.reduce((sum,c)=>sum+c.weight,0);
  function update(id: string, patch: Partial<RubricCriterion>) { setCriteria(current=>current.map(c=>c.id===id?{...c,...patch}:c)); }
  function save(e: FormEvent<HTMLFormElement>) { e.preventDefault(); void saveRubric(criteria); }
  return <form className="organizer-rubric-form" onSubmit={save}><fieldset className="organizer-fields" disabled={busy}><section className="organizer-rubric-card"><div className="organizer-rubric-columns"><span>CRITERION</span><span>DESCRIPTION</span><span>WEIGHT %</span><span>MAX SCORE</span></div>{criteria.map(c=><article className="organizer-rubric-row" key={c.id}><label className="event-field"><span className="sr-only">Criterion name</span><input required value={c.name} onChange={e=>update(c.id,{name:e.target.value})} /></label><label className="event-field"><span className="sr-only">{c.name} description</span><textarea value={c.description} onChange={e=>update(c.id,{description:e.target.value})} /></label><label className="organizer-rubric-input"><span className="sr-only">{c.name} weight</span><input required type="number" min={0} max={100} step="any" value={c.weight} onChange={e=>update(c.id,{weight:Number(e.target.value)})} /></label><label className="organizer-rubric-input"><span className="sr-only">{c.name} maximum score</span><input required type="number" min={1} step="any" value={c.max_score} onChange={e=>update(c.id,{max_score:Number(e.target.value)})} /></label></article>)}</section><section className="organizer-rubric-footer"><div><p className="metadata">TOTAL WEIGHT</p><strong>{total}%</strong><span>Must total 100%. Rubric edits are locked once scoring starts.</span></div><button className="button button-primary" disabled={!criteria.length} type="submit">Save rubric</button></section></fieldset></form>;
}
export function OrganizerRubricPage() { const { snapshot } = useOrganizer(); if (!snapshot) return null; return <><section className="workspace-intro"><div><p className="eyebrow">[ ORGANIZER / RUBRIC ]</p><h1>SCORING RUBRIC<span className="heading-period">.</span></h1><p className="workspace-description">{snapshot.event?.name} / Shared judging criteria and score ranges.</p></div></section><RubricEditor key={JSON.stringify(snapshot.rubric)} initial={snapshot.rubric} /></>; }
