import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useOrganizer } from '../../organizer/OrganizerProvider';
import { paths } from '../../routes';
export function OrganizerProjectsPage() {
  const { snapshot } = useOrganizer(); const [query,setQuery] = useState(''); if (!snapshot) return null;
  const rows = snapshot.projects.map(project => ({ ...project, team: snapshot.teams.find(team=>team.id===project.team_id)?.name ?? 'Unknown team', track: snapshot.tracks.find(track=>track.id===project.track_id)?.name ?? 'Unassigned' })).filter(project => `${project.title} ${project.team} ${project.track}`.toLowerCase().includes(query.trim().toLowerCase()));
  return <><section className="workspace-intro"><div><p className="eyebrow">[ ORGANIZER / PROJECTS ]</p><h1>PROJECTS<span className="heading-period">.</span></h1><p className="workspace-description">Review submitted projects across the event.</p></div><span className="badge badge-cyan">{snapshot.projects.length} RECORDS</span></section><section className="organizer-projects-toolbar"><strong>EVENT SUBMISSIONS</strong><label className="organizer-search"><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search projects" aria-label="Search projects" /></label></section><section className="organizer-project-table"><div className="organizer-project-header"><span>PROJECT</span><span>TEAM</span><span>TRACK</span><span>STATUS</span><span>ACTION</span></div>{rows.map(project => <article className="organizer-project-row" key={project.id}><strong>{project.title}</strong><span>{project.team}</span><span>{project.track}</span><span className="badge badge-muted">{project.status}</span>{project.state === 'submitted' ? <Link className="organizer-project-view" to={paths.project(project.id,project.event_id)}>View ↗</Link> : <span className="metadata">Private draft</span>}</article>)}{!rows.length && <p className="team-message">No projects match.</p>}</section></>;
}
