import { useState } from 'react';
import { useOrganizer } from '../../organizer/OrganizerProvider';
import { organizerProgress } from '../../organizer/data';
export function OrganizerJudgeAssignmentsPage() {
  const { snapshot,busy,assignJudges } = useOrganizer(); const [query,setQuery] = useState(''); if (!snapshot) return null;
  const progress = organizerProgress(snapshot.assignments);
  const judges = snapshot.judges.map(judge=>({...judge, track: snapshot.tracks.filter(t=>judge.track_ids.includes(t.id)).map(t=>t.name).join(', '), progress: organizerProgress(snapshot.assignments.filter(a=>a.judge_id===judge.id))})).filter(judge=>`${judge.name} ${judge.track}`.toLowerCase().includes(query.trim().toLowerCase()));
  return <><section className="workspace-intro"><div><p className="eyebrow">[ ORGANIZER / JUDGES ]</p><h1>JUDGE ASSIGNMENTS<span className="heading-period">.</span></h1><p className="workspace-description">Fill eligible review slots and monitor coverage.</p></div><button className="button button-primary" type="button" disabled={busy} onClick={()=>void assignJudges()}>Generate assignments ↗</button></section><section className="organizer-judge-metrics">{[{label:'ASSIGNED',value:progress.assigned},{label:'COMPLETED',value:progress.completed},{label:'REMAINING',value:progress.remaining},{label:'PROGRESS',value:progress.percentage+'%'}].map(item=><article key={item.label}><p className="metadata">{item.label}</p><strong>{item.value}</strong></article>)}</section><section className="organizer-judge-toolbar"><strong>ASSIGNMENT COVERAGE / {snapshot.judges.length} JUDGES</strong><label className="organizer-search"><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search judges or tracks" aria-label="Search judges or tracks" /></label></section><section className="organizer-judge-table"><div className="organizer-judge-header"><span>JUDGE</span><span>TRACK</span><span>ASSIGNED</span><span>COMPLETED</span><span>PROGRESS</span></div>{judges.map(judge=><article className="organizer-judge-row" key={judge.id}><strong>{judge.name}</strong><span>{judge.track || 'No eligible tracks'}</span><strong>{judge.progress.assigned}</strong><strong>{judge.progress.completed}</strong><div><progress value={judge.progress.completed} max={judge.progress.assigned || 1} aria-label={`${judge.name} completion`} /><span>{judge.progress.percentage}% / {judge.progress.remaining} remaining</span></div></article>)}{!judges.length && <p className="team-message">No judges match.</p>}</section><p className="team-message">Only progress counts are shown. Generation respects existing assignments, track eligibility and team conflicts.</p></>;
}
