import { Link } from 'react-router-dom';
import { useOrganizer } from '../../organizer/OrganizerProvider';
import { organizerProgress } from '../../organizer/data';
import { paths } from '../../routes';
export function OrganizerDashboard() {
  const { snapshot } = useOrganizer(); if (!snapshot?.event) return null;
  const { event, projects, teams, judges, assignments } = snapshot;
  const progress = organizerProgress(assignments);
  return <>
    <section className="workspace-intro"><div><p className="eyebrow">[ ORGANIZER WORKSPACE ]</p><h1>ARENA CONTROL<span className="heading-period">.</span></h1><p className="workspace-description">Monitor submissions, judging and event progress from one place.</p></div><Link className="button button-primary" to={paths.organizer.judges}>Manage judging ↗</Link></section>
    <section className="panel event-status"><header className="panel-header"><h2><span>//</span> Event Status</h2><span className="badge badge-cyan">{event.closed ? 'SUBMISSIONS CLOSED' : 'SUBMISSIONS OPEN'}</span></header><div className="event-status-body"><div className="event-summary"><p className="metadata">CURRENT ARENA</p><h3>{event.name}</h3><p>{event.description}</p><p>Submission deadline: {new Date(event.submissions_close).toLocaleString('en-GB', { timeZone: 'UTC' })} UTC</p><Link to={paths.organizer.events}>Event settings ↗</Link></div><div className="review-progress"><div className="progress-heading"><span className="metadata">REVIEW COMPLETION</span><strong>{progress.percentage}<span>%</span></strong></div><progress value={progress.completed} max={progress.assigned || 1} aria-label="Review completion" /><div className="progress-caption"><span>{progress.completed} / {progress.assigned} assigned reviews</span><span>{progress.remaining} remaining</span></div></div></div></section>
    <section className="metric-strip" aria-label="Event metrics">{[{label:'PROJECTS',value:projects.length},{label:'TEAMS',value:teams.length},{label:'JUDGES',value:judges.length},{label:'COMPLETED REVIEWS',value:progress.completed}].map(item => <div className="metric" key={item.label}><p className="metric-label">{item.label}</p><strong className="metric-value">{item.value}</strong></div>)}</section>
    <div className="dashboard-lower"><section className="panel"><header className="panel-header"><h2><span>//</span> Project Feed</h2><Link to={paths.organizer.projects}>ALL PROJECTS ↗</Link></header><ul className="project-list">{projects.slice(0,4).map(project => <li className="project-row" key={project.id}><span className="project-number">{project.id}</span><div className="project-copy"><h3><Link to={paths.organizer.projects}>{project.title}</Link></h3><p>{teams.find(team => team.id === project.team_id)?.name}</p></div><span className="badge badge-muted">{project.status}</span></li>)}</ul>{!projects.length && <p className="team-message">No projects yet.</p>}</section><section className="panel"><header className="panel-header"><h2><span>//</span> Next Moves</h2></header><ol className="next-moves">{[{title:'Manage the event',to:paths.organizer.events},{title:'Check judging coverage',to:paths.organizer.judges},{title:'Review results',to:paths.organizer.results}].map((item,index) => <li key={item.to}><span className="move-number">0{index+1}</span><Link to={item.to}>{item.title} ↗</Link></li>)}</ol></section></div>
  </>;
}
