import { useState } from 'react';
import { useOrganizer } from '../../organizer/OrganizerProvider';
import { organizerProgress } from '../../organizer/data';
export function OrganizerResultsPage() {
  const { snapshot,busy,exportResults,publish } = useOrganizer(); const [query,setQuery] = useState(''); if (!snapshot) return null;
  const progress = organizerProgress(snapshot.assignments);
  const rows = snapshot.results.items.map(result=>({...result,team:snapshot.teams.find(t=>t.id===result.team_id)?.name ?? 'Unknown team',track:snapshot.tracks.find(t=>t.id===result.track_id)?.name ?? 'Unassigned'})).filter(row=>`${row.title} ${row.team} ${row.track}`.toLowerCase().includes(query.trim().toLowerCase()));
  const complete = snapshot.results.items.length > 0 && snapshot.results.items.every(item=>item.complete);
  const score = (value: number | null) => value == null ? '—' : value.toFixed(2);
  return <><section className="workspace-intro"><div><p className="eyebrow">[ ORGANIZER / RESULTS ]</p><h1>RESULTS & EXPORTS<span className="heading-period">.</span></h1><p className="workspace-description">Calculated results from submitted evaluations.</p></div><span className="badge badge-cyan">{snapshot.results.published?'PUBLISHED':'PRIVATE'}</span></section><section className="organizer-result-metrics">{[{label:'SUBMITTED PROJECTS',value:snapshot.results.items.length},{label:'REVIEWS',value:progress.completed},{label:'ASSIGNED',value:progress.assigned},{label:'COMPLETION',value:progress.percentage+'%'}].map(item=><article key={item.label}><p className="metadata">{item.label}</p><strong>{item.value}</strong></article>)}</section><section className="organizer-results-toolbar"><div><p className="metadata">{complete?'REQUIRED REVIEWS COMPLETE':'INCOMPLETE JUDGING'}</p><strong>NORMALIZED RANKING</strong></div><div className="organizer-results-controls"><label className="organizer-search"><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search results" aria-label="Search project results" /></label><button className="button button-primary" type="button" disabled={busy} onClick={()=>void exportResults()}>Export CSV</button><button className="button public-secondary" type="button" disabled={busy || (!snapshot.results.published && !complete)} onClick={()=>void publish(!snapshot.results.published)}>{snapshot.results.published?'Make private':'Publish results'}</button></div></section><section className="organizer-results-table"><div className="organizer-results-header"><span>RANK</span><span>PROJECT</span><span>TEAM</span><span>TRACK</span><span>REVIEWS</span><span>RAW / 100</span><span>NORMALIZED / 100</span></div>{rows.map(row=><article className="organizer-results-row" key={row.project_id}><strong>{row.rank ?? '—'}</strong><div><strong>{row.title}</strong><p className="metadata">{row.complete?'COMPLETE':'INCOMPLETE / UNRANKED'}</p></div><span>{row.team}</span><span>{row.track}</span><span>{row.reviews} / {row.required}</span><span>{score(row.raw_score)}</span><strong className="organizer-normalized-score">{score(row.score)}</strong></article>)}{!rows.length && <p className="team-message">No results match.</p>}</section><section className="organizer-normalization-note"><p className="metadata">NORMALIZATION / {snapshot.results.method}</p><p>Scores come from the shared results API. Missing scores remain blank; projects with insufficient reviews remain unranked. Partial scores are provisional.</p></section></>;
}
