"""add project comments

Revision ID: 0b687712aa84
Revises: a7f4ca2782a3
Create Date: 2026-09-28 19:38:22.903958
"""
from alembic import op
import sqlalchemy as sa



revision = '0b687712aa84'
down_revision = 'a7f4ca2782a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='fk_project_comments_author', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'event_id'], ['project_submissions.id', 'project_submissions.event_id'], name='fk_project_comments_project_event', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_comments_project_event_created', 'project_comments', ['project_id', 'event_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_comments_project_event_created', table_name='project_comments')
    op.drop_table('project_comments')
    # ### end Alembic commands ###
