"""add DOGFOOD judging

Revision ID: 3866dd34436e
Revises: b157a27eacda
Create Date: 2026-09-27 12:13:26.681160
"""
from alembic import op
import sqlalchemy as sa



revision = '3866dd34436e'
down_revision = 'b157a27eacda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dogfood_judge_event_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('judge_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'revoked')", name='ck_dogfood_event_judge_status'),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['judge_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'judge_id', name='uq_dogfood_event_judge')
    )
    op.create_index('ix_dogfood_event_judges_event_status', 'dogfood_judge_event_assignments', ['event_id', 'status'], unique=False)
    op.create_table('dogfood_rubrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'active', 'archived')", name='ck_dogfood_rubrics_status'),
    sa.CheckConstraint('version >= 1', name='ck_dogfood_rubrics_version_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'version', name='uq_dogfood_rubrics_event_version'),
    sa.UniqueConstraint('id', 'event_id', name='uq_dogfood_rubrics_id_event')
    )
    op.create_index('uq_dogfood_rubrics_one_active_per_event', 'dogfood_rubrics', ['event_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('dogfood_judging_result_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('rubric_id', sa.Uuid(), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('method_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('insufficient_reason', sa.Text(), nullable=True),
    sa.Column('source_evaluation_count', sa.Integer(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ready', 'insufficient_data')", name='ck_dogfood_snapshot_status'),
    sa.CheckConstraint('source_evaluation_count >= 0', name='ck_dogfood_snapshot_source_count'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rubric_id', 'event_id'], ['dogfood_rubrics.id', 'dogfood_rubrics.event_id'], name='fk_dogfood_snapshot_rubric_event', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'event_id', name='uq_dogfood_snapshot_id_event')
    )
    op.create_index('ix_dogfood_snapshots_event_created', 'dogfood_judging_result_snapshots', ['event_id', 'created_at'], unique=False)
    op.create_table('dogfood_rubric_criteria',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rubric_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.CheckConstraint('max_score > 0', name='ck_dogfood_criteria_max_score_positive'),
    sa.CheckConstraint('position >= 0', name='ck_dogfood_criteria_position_nonnegative'),
    sa.CheckConstraint('weight > 0', name='ck_dogfood_criteria_weight_positive'),
    sa.ForeignKeyConstraint(['rubric_id', 'event_id'], ['dogfood_rubrics.id', 'dogfood_rubrics.event_id'], name='fk_dogfood_criteria_rubric_event', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'rubric_id', name='uq_dogfood_criteria_id_rubric'),
    sa.UniqueConstraint('rubric_id', 'position', name='uq_dogfood_criteria_position')
    )
    op.create_index('ix_dogfood_criteria_rubric', 'dogfood_rubric_criteria', ['rubric_id', 'position'], unique=False)
    op.create_unique_constraint('uq_project_submissions_id_event', 'project_submissions', ['id', 'event_id'])
    op.create_table('dogfood_judge_project_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('judge_id', sa.Uuid(), nullable=False),
    sa.Column('rubric_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'in_progress', 'submitted', 'revoked')", name='ck_dogfood_project_assignment_status'),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id', 'judge_id'], ['dogfood_judge_event_assignments.event_id', 'dogfood_judge_event_assignments.judge_id'], name='fk_dogfood_project_assignment_event_judge', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'event_id'], ['project_submissions.id', 'project_submissions.event_id'], name='fk_dogfood_project_assignment_project_event', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rubric_id', 'event_id'], ['dogfood_rubrics.id', 'dogfood_rubrics.event_id'], name='fk_dogfood_project_assignment_rubric_event', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'event_id', 'judge_id', 'rubric_id', name='uq_dogfood_assignment_scope'),
    sa.UniqueConstraint('project_id', 'judge_id', name='uq_dogfood_project_judge')
    )
    op.create_index('ix_dogfood_project_assignments_event', 'dogfood_judge_project_assignments', ['event_id', 'project_id'], unique=False)
    op.create_index('ix_dogfood_project_assignments_judge_status', 'dogfood_judge_project_assignments', ['judge_id', 'status'], unique=False)
    op.create_table('dogfood_judging_project_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('raw_average', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('normalized_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('evaluation_count', sa.Integer(), nullable=False),
    sa.CheckConstraint('evaluation_count > 0', name='ck_dogfood_result_evaluation_count'),
    sa.CheckConstraint('normalized_score IS NULL OR (normalized_score >= 0 AND normalized_score <= 100)', name='ck_dogfood_result_normalized_range'),
    sa.CheckConstraint('raw_average >= 0 AND raw_average <= 100', name='ck_dogfood_result_raw_range'),
    sa.ForeignKeyConstraint(['project_id', 'event_id'], ['project_submissions.id', 'project_submissions.event_id'], name='fk_dogfood_project_result_project_event', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id', 'event_id'], ['dogfood_judging_result_snapshots.id', 'dogfood_judging_result_snapshots.event_id'], name='fk_dogfood_project_result_snapshot_event', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'project_id', name='uq_dogfood_snapshot_project')
    )
    op.create_index('ix_dogfood_project_results_snapshot_rank', 'dogfood_judging_project_results', ['snapshot_id', 'normalized_score'], unique=False)
    op.create_table('dogfood_judge_evaluations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('judge_id', sa.Uuid(), nullable=False),
    sa.Column('rubric_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('feedback', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('weighted_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'submitted')", name='ck_dogfood_evaluation_status'),
    sa.CheckConstraint("(status = 'draft' AND submitted_at IS NULL) OR (status = 'submitted' AND submitted_at IS NOT NULL)", name='ck_dogfood_evaluation_submitted_at'),
    sa.CheckConstraint('weighted_score IS NULL OR (weighted_score >= 0 AND weighted_score <= 100)', name='ck_dogfood_evaluation_weighted_score'),
    sa.ForeignKeyConstraint(['assignment_id', 'event_id', 'judge_id', 'rubric_id'], ['dogfood_judge_project_assignments.id', 'dogfood_judge_project_assignments.event_id', 'dogfood_judge_project_assignments.judge_id', 'dogfood_judge_project_assignments.rubric_id'], name='fk_dogfood_evaluation_assignment_scope', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', name='uq_dogfood_evaluation_assignment'),
    sa.UniqueConstraint('id', 'rubric_id', name='uq_dogfood_evaluation_id_rubric')
    )
    op.create_index('ix_dogfood_evaluations_event_status', 'dogfood_judge_evaluations', ['event_id', 'status'], unique=False)
    op.create_table('dogfood_judge_criterion_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evaluation_id', sa.Uuid(), nullable=False),
    sa.Column('criterion_id', sa.Uuid(), nullable=False),
    sa.Column('rubric_id', sa.Uuid(), nullable=False),
    sa.Column('raw_score', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('raw_score >= 0', name='ck_dogfood_raw_score_nonnegative'),
    sa.ForeignKeyConstraint(['criterion_id', 'rubric_id'], ['dogfood_rubric_criteria.id', 'dogfood_rubric_criteria.rubric_id'], name='fk_dogfood_score_criterion_rubric', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['evaluation_id', 'rubric_id'], ['dogfood_judge_evaluations.id', 'dogfood_judge_evaluations.rubric_id'], name='fk_dogfood_score_evaluation_rubric', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluation_id', 'criterion_id', name='uq_dogfood_score_criterion')
    )
    op.create_index('ix_dogfood_scores_evaluation', 'dogfood_judge_criterion_scores', ['evaluation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dogfood_scores_evaluation', table_name='dogfood_judge_criterion_scores')
    op.drop_table('dogfood_judge_criterion_scores')
    op.drop_index('ix_dogfood_evaluations_event_status', table_name='dogfood_judge_evaluations')
    op.drop_table('dogfood_judge_evaluations')
    op.drop_index('ix_dogfood_project_results_snapshot_rank', table_name='dogfood_judging_project_results')
    op.drop_table('dogfood_judging_project_results')
    op.drop_index('ix_dogfood_project_assignments_judge_status', table_name='dogfood_judge_project_assignments')
    op.drop_index('ix_dogfood_project_assignments_event', table_name='dogfood_judge_project_assignments')
    op.drop_table('dogfood_judge_project_assignments')
    op.drop_index('ix_dogfood_criteria_rubric', table_name='dogfood_rubric_criteria')
    op.drop_table('dogfood_rubric_criteria')
    op.drop_index('ix_dogfood_snapshots_event_created', table_name='dogfood_judging_result_snapshots')
    op.drop_table('dogfood_judging_result_snapshots')
    op.drop_index('uq_dogfood_rubrics_one_active_per_event', table_name='dogfood_rubrics', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('dogfood_rubrics')
    op.drop_index('ix_dogfood_event_judges_event_status', table_name='dogfood_judge_event_assignments')
    op.drop_table('dogfood_judge_event_assignments')
    op.drop_constraint('uq_project_submissions_id_event', 'project_submissions', type_='unique')
    # ### end Alembic commands ###
