"""add dogfood t1 domain

Revision ID: a34bfedd5478
Revises: 7e3a91f2c6b4
Create Date: 2026-09-27 04:24:26.777358
"""

from alembic import op
import sqlalchemy as sa


revision = "a34bfedd5478"
down_revision = "7e3a91f2c6b4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "ck_users_role", "users", "role IN ('participant', 'organizer', 'admin')"
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organizer_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.String(length=24),
            server_default=sa.text("'draft'"),
            nullable=False,
        ),
        sa.Column("registration_opens_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("registration_deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("submission_deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("team_min_size", sa.Integer(), nullable=False),
        sa.Column("team_max_size", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'active', 'completed', 'cancelled')",
            name="ck_events_status",
        ),
        sa.CheckConstraint(
            "registration_opens_at <= registration_deadline AND registration_deadline <= starts_at AND starts_at <= submission_deadline AND submission_deadline <= ends_at",
            name="ck_events_schedule_order",
        ),
        sa.CheckConstraint(
            "team_max_size >= team_min_size", name="ck_events_team_max_size_gte_min"
        ),
        sa.CheckConstraint(
            "team_min_size >= 1", name="ck_events_team_min_size_positive"
        ),
        sa.ForeignKeyConstraint(["organizer_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug", name="uq_events_slug"),
    )
    op.create_index(
        op.f("ix_events_organizer_id"), "events", ["organizer_id"], unique=False
    )
    op.create_table(
        "event_registrations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "event_id", "user_id", name="uq_event_registrations_event_user"
        ),
    )
    op.create_index(
        op.f("ix_event_registrations_event_id"),
        "event_registrations",
        ["event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_registrations_user_id"),
        "event_registrations",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("captain_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["captain_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "event_id", name="uq_teams_id_event"),
    )
    op.create_index("ix_teams_event_id", "teams", ["event_id"], unique=False)
    op.create_table(
        "project_submissions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column(
            "description", sa.Text(), server_default=sa.text("''"), nullable=False
        ),
        sa.Column("repository_url", sa.String(length=2048), nullable=True),
        sa.Column("demo_url", sa.String(length=2048), nullable=True),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default=sa.text("'draft'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('draft', 'submitted')", name="ck_project_submissions_status"
        ),
        sa.ForeignKeyConstraint(
            ["team_id", "event_id"],
            ["teams.id", "teams.event_id"],
            name="fk_project_submissions_team_event",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id", name="uq_project_submissions_team"),
    )
    op.create_index(
        "ix_project_submissions_event_status_submitted",
        "project_submissions",
        ["event_id", "status", "submitted_at"],
        unique=False,
    )
    op.create_table(
        "team_invitations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("inviter_id", sa.Uuid(), nullable=False),
        sa.Column("invitee_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'accepted', 'revoked', 'expired')",
            name="ck_team_invitations_status",
        ),
        sa.ForeignKeyConstraint(
            ["event_id", "invitee_id"],
            ["event_registrations.event_id", "event_registrations.user_id"],
            name="fk_team_invitations_registration",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["invitee_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["inviter_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["team_id", "event_id"],
            ["teams.id", "teams.event_id"],
            name="fk_team_invitations_team_event",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "team_id", "invitee_id", name="uq_team_invitations_team_invitee"
        ),
        sa.UniqueConstraint("token_hash", name="uq_team_invitations_token_hash"),
    )
    op.create_index(
        "ix_team_invitations_invitee_status",
        "team_invitations",
        ["invitee_id", "status"],
        unique=False,
    )
    op.create_table(
        "team_members",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id", "user_id"],
            ["event_registrations.event_id", "event_registrations.user_id"],
            name="fk_team_members_registration",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["team_id", "event_id"],
            ["teams.id", "teams.event_id"],
            name="fk_team_members_team_event",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("event_id", "user_id"),
    )
    op.create_index(
        "ix_team_members_team_id", "team_members", ["team_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_team_members_team_id", table_name="team_members")
    op.drop_table("team_members")
    op.drop_index("ix_team_invitations_invitee_status", table_name="team_invitations")
    op.drop_table("team_invitations")
    op.drop_index(
        "ix_project_submissions_event_status_submitted",
        table_name="project_submissions",
    )
    op.drop_table("project_submissions")
    op.drop_index("ix_teams_event_id", table_name="teams")
    op.drop_table("teams")
    op.drop_index(
        op.f("ix_event_registrations_user_id"), table_name="event_registrations"
    )
    op.drop_index(
        op.f("ix_event_registrations_event_id"), table_name="event_registrations"
    )
    op.drop_table("event_registrations")
    op.drop_index(op.f("ix_events_organizer_id"), table_name="events")
    op.drop_table("events")
    op.drop_constraint("ck_users_role", "users", type_="check")
    # ### end Alembic commands ###
