"""add_community_voting

Revision ID: a7f4ca2782a3
Revises: d06f00d2026a
Create Date: 2026-09-28 00:36:58.282872
"""
from alembic import op
import sqlalchemy as sa



revision = 'a7f4ca2782a3'
down_revision = 'd06f00d2026a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dogfood_votes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('voter_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id', 'event_id'], ['project_submissions.id', 'project_submissions.event_id'], name='fk_dogfood_votes_project_event', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'voter_id', name='uq_dogfood_votes_project_voter')
    )
    op.create_index(op.f('ix_dogfood_votes_event_id'), 'dogfood_votes', ['event_id'], unique=False)
    op.create_index('ix_dogfood_votes_event_voter', 'dogfood_votes', ['event_id', 'voter_id'], unique=False)
    op.create_index('ix_dogfood_votes_project', 'dogfood_votes', ['project_id'], unique=False)
    op.create_index(op.f('ix_dogfood_votes_voter_id'), 'dogfood_votes', ['voter_id'], unique=False)
    op.add_column('events', sa.Column('voting_opens_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('events', sa.Column('voting_ends_at', sa.DateTime(timezone=True), nullable=True))
    op.create_check_constraint(
        'ck_events_voting_schedule_order',
        'events',
        'voting_opens_at IS NULL OR voting_ends_at IS NULL OR voting_opens_at <= voting_ends_at',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_events_voting_schedule_order', 'events', type_='check')
    op.drop_column('events', 'voting_ends_at')
    op.drop_column('events', 'voting_opens_at')
    op.drop_index(op.f('ix_dogfood_votes_voter_id'), table_name='dogfood_votes')
    op.drop_index('ix_dogfood_votes_project', table_name='dogfood_votes')
    op.drop_index('ix_dogfood_votes_event_voter', table_name='dogfood_votes')
    op.drop_index(op.f('ix_dogfood_votes_event_id'), table_name='dogfood_votes')
    op.drop_table('dogfood_votes')
    # ### end Alembic commands ###
