"""enforce dogfood ownership constraints

Revision ID: b157a27eacda
Revises: a34bfedd5478
Create Date: 2026-09-27 04:33:49.713837
"""

from alembic import op


revision = "b157a27eacda"
down_revision = "a34bfedd5478"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_teams_captain_registration",
        "teams",
        "event_registrations",
        ["event_id", "captain_id"],
        ["event_id", "user_id"],
        ondelete="RESTRICT",
    )
    op.create_check_constraint(
        "ck_project_submissions_submitted_at",
        "project_submissions",
        "(status = 'draft' AND submitted_at IS NULL) OR "
        "(status = 'submitted' AND submitted_at IS NOT NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_project_submissions_submitted_at", "project_submissions", type_="check"
    )
    op.drop_constraint("fk_teams_captain_registration", "teams", type_="foreignkey")
    # ### end Alembic commands ###
