"""add voting audit logs

Revision ID: dc5f40b09308
Revises: 0b687712aa84
Create Date: 2026-09-28 21:45:42.475977
"""
from alembic import op
import sqlalchemy as sa



revision = 'dc5f40b09308'
down_revision = '0b687712aa84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dogfood_voting_audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('voter_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project_submissions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['voter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dogfood_voting_audit_event_created', 'dogfood_voting_audit_logs', ['event_id', 'created_at'], unique=False)
    op.create_index('ix_dogfood_voting_audit_voter_created', 'dogfood_voting_audit_logs', ['voter_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dogfood_voting_audit_voter_created', table_name='dogfood_voting_audit_logs')
    op.drop_index('ix_dogfood_voting_audit_event_created', table_name='dogfood_voting_audit_logs')
    op.drop_table('dogfood_voting_audit_logs')
    # ### end Alembic commands ###
